services:
  web:
    image: flourish-web
    build: ./client
    ports:
      - "8080:3000"
    depends_on: [api]
  api:
    image: flourish-api
    build: ./server/Flourish.API
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:5000"
      - "8082:5001"
    depends_on: [redis]
  redis:
    image: "redis:alpine"
